// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod openfab {
  pub mod drivers {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod serialport {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[derive(Clone)]
      pub struct Portinfo {
        pub name: _rt::String,
        pub porttype: u16,
      }
      impl ::core::fmt::Debug for Portinfo {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Portinfo").field("name", &self.name).field("porttype", &self.porttype).finish()
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn listports() -> Result<_rt::Vec::<Portinfo>,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "openfab:drivers/serialport")]
          unsafe extern "C" {
            #[link_name = "listports"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ){ unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result13 = match l2 {
            0 => {
              let e = {
                let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let base9 = l3;
                let len9 = l4;
                let mut result9 = _rt::Vec::with_capacity(len9);
                for i in 0..len9 {
                  let base = base9.add(i * (3*::core::mem::size_of::<*const u8>()));
                  let e9 = {
                    let l5 = *base.add(0).cast::<*mut u8>();
                    let l6 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len7 = l6;
                    let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                    let l8 = i32::from(*base.add(2*::core::mem::size_of::<*const u8>()).cast::<u16>());

                    Portinfo{
                      name: _rt::string_lift(bytes7),
                      porttype: l8 as u16,
                    }
                  };
                  result9.push(e9);
                }
                _rt::cabi_dealloc(base9, len9 * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                result9
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l10 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l11 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len12 = l11;
                let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                _rt::string_lift(bytes12)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result13
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn open(path: &str,baudrate: u32,) -> Result<_rt::String,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "openfab:drivers/serialport")]
          unsafe extern "C" {
            #[link_name = "open"]
            fn wit_import2(_: *mut u8, _: usize, _: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: i32, _: *mut u8, ){ unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, _rt::as_i32(&baudrate), ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result10 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                _rt::string_lift(bytes6)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l7 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l8 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len9 = l8;
                let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                _rt::string_lift(bytes9)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result10
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn write(path: &str,data: &[u8],) -> Result<u64,_rt::String>{
        unsafe {

          #[repr(align(8))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 8+2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8+2*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = data;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "openfab:drivers/serialport")]
          unsafe extern "C" {
            #[link_name = "write"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result9 = match l4 {
            0 => {
              let e = {
                let l5 = *ptr2.add(8).cast::<i64>();

                l5 as u64
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l6 = *ptr2.add(8).cast::<*mut u8>();
                let l7 = *ptr2.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len8 = l7;
                let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                _rt::string_lift(bytes8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn read(path: &str,) -> Result<_rt::Vec::<u8>,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "openfab:drivers/serialport")]
          unsafe extern "C" {
            #[link_name = "read"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result10 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;

                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l7 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l8 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len9 = l8;
                let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                _rt::string_lift(bytes9)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result10
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn close(path: &str,) -> Result<u16,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "openfab:drivers/serialport")]
          unsafe extern "C" {
            #[link_name = "close"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result8 = match l3 {
            0 => {
              let e = {
                let l4 = i32::from(*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u16>());

                l4 as u16
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;
                let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                _rt::string_lift(bytes7)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result8
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod openfab {
    pub mod drivers {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod driver {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[derive(Clone)]
        pub struct Job {
          pub id: u64,
          pub name: _rt::String,
          pub format: _rt::String,
          pub data: _rt::Vec::<u8>,
        }
        impl ::core::fmt::Debug for Job {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Job").field("id", &self.id).field("name", &self.name).field("format", &self.format).field("data", &self.data).finish()
          }
        }

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Driver{
          handle: _rt::Resource<Driver>,
        }

        type _DriverRep<T> = Option<T>;

        impl Driver{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Driver`.
          pub fn new<T: GuestDriver>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _DriverRep<T> = Some(val);
            let ptr: *mut _DriverRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestDriver>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestDriver>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestDriver>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestDriver` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _DriverRep<T>) };
          }

          fn as_ptr<T: GuestDriver>(&self) -> *mut _DriverRep<T> {
            Driver::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Driver`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct DriverBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Driver>,
        }

        impl<'a> DriverBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestDriver>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _DriverRep<T> {
            Driver::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Driver{
          #[inline]
          unsafe fn drop(_handle: u32) {
            #[cfg(not(target_arch = "wasm32"))]
            unreachable!();

            #[cfg(target_arch = "wasm32")]
            {
              #[link(wasm_import_module = "[export]openfab:drivers/driver")]
              unsafe extern "C" {
                #[link_name = "[resource-drop]driver"]
                fn drop(_: u32);
              }

              unsafe { drop(_handle) };
            }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_constructor_driver_cabi<T: GuestDriver>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          Driver::new(T::new())
        };
        (result0).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_driver_init_cabi<T: GuestDriver>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T::init(DriverBorrow::lift(arg0 as u32 as usize).get())
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result0 {
        Ok(e) => { {
          *ptr1.add(0).cast::<u8>() = (0i32) as u8;
          *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
        } },
        Err(e) => { {
          *ptr1.add(0).cast::<u8>() = (1i32) as u8;
          let vec2 = (e.into_bytes()).into_boxed_slice();
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          ::core::mem::forget(vec2);
          *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
          *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
        } },
      };ptr1
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_method_driver_init<T: GuestDriver>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => (),
        _ => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l1, l2, 1);
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_method_driver_shutdown_cabi<T: GuestDriver>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result0 = {
      T::shutdown(DriverBorrow::lift(arg0 as u32 as usize).get())
    };
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
      Ok(e) => { {
        *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
      } },
      Err(e) => { {
        *ptr1.add(0).cast::<u8>() = (1i32) as u8;
        let vec2 = (e.into_bytes()).into_boxed_slice();
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        ::core::mem::forget(vec2);
        *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
      } },
    };ptr1
  } }
  #[doc(hidden)]
  #[allow(non_snake_case)]
  pub unsafe fn __post_return_method_driver_shutdown<T: GuestDriver>(arg0: *mut u8,) { unsafe {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
      0 => (),
      _ => {
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l1, l2, 1);
      },
    }
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_method_driver_startjob_cabi<T: GuestDriver>(arg0: *mut u8,arg1: i64,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result3 = {
    let len0 = arg3;
    let bytes0 = _rt::Vec::from_raw_parts(arg2.cast(), len0, len0);
    let len1 = arg5;
    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
    let len2 = arg7;
    T::startjob(DriverBorrow::lift(arg0 as u32 as usize).get(), Job{
      id: arg1 as u64,
      name: _rt::string_lift(bytes0),
      format: _rt::string_lift(bytes1),
      data: _rt::Vec::from_raw_parts(arg6.cast(), len2, len2),
    })
  };
  let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
  match result3 {
    Ok(e) => { {
      *ptr4.add(0).cast::<u8>() = (0i32) as u8;
      *ptr4.add(8).cast::<i64>() = _rt::as_i64(e);
    } },
    Err(e) => { {
      *ptr4.add(0).cast::<u8>() = (1i32) as u8;
      let vec5 = (e.into_bytes()).into_boxed_slice();
      let ptr5 = vec5.as_ptr().cast::<u8>();
      let len5 = vec5.len();
      ::core::mem::forget(vec5);
      *ptr4.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
      *ptr4.add(8).cast::<*mut u8>() = ptr5.cast_mut();
    } },
  };ptr4
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_driver_startjob<T: GuestDriver>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(8).cast::<*mut u8>();
      let l2 = *arg0.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_driver_pausejob_cabi<T: GuestDriver>(arg0: *mut u8,arg1: i64,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::pausejob(DriverBorrow::lift(arg0 as u32 as usize).get(), arg1 as u64)
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Ok(e) => { {
    *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
  } },
  Err(e) => { {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    let vec2 = (e.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
  } },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_driver_pausejob<T: GuestDriver>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_method_driver_stopjob_cabi<T: GuestDriver>(arg0: *mut u8,arg1: i64,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::stopjob(DriverBorrow::lift(arg0 as u32 as usize).get(), arg1 as u64)
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Ok(e) => { {
    *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
  } },
  Err(e) => { {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    let vec2 = (e.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
  } },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_method_driver_stopjob<T: GuestDriver>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
  }
} }
pub trait Guest {
  type Driver: GuestDriver;
}
pub trait GuestDriver: 'static {

  #[doc(hidden)]
  unsafe fn _resource_new(val: *mut u8) -> u32
  where Self: Sized
  {
    #[cfg(not(target_arch = "wasm32"))]
    {
      let _ = val;
      unreachable!();
    }

    #[cfg(target_arch = "wasm32")]
    {
      #[link(wasm_import_module = "[export]openfab:drivers/driver")]
      unsafe extern "C" {
        #[link_name = "[resource-new]driver"]
        fn new(_: *mut u8) -> u32;
      }
      unsafe { new(val) }
    }
  }

  #[doc(hidden)]
  fn _resource_rep(handle: u32) -> *mut u8
  where Self: Sized
  {
    #[cfg(not(target_arch = "wasm32"))]
    {
      let _ = handle;
      unreachable!();
    }

    #[cfg(target_arch = "wasm32")]
    {
      #[link(wasm_import_module = "[export]openfab:drivers/driver")]
      unsafe extern "C" {
        #[link_name = "[resource-rep]driver"]
        fn rep(_: u32) -> *mut u8;
      }
      unsafe {
        rep(handle)
      }
    }
  }

  
  #[allow(async_fn_in_trait)]
  fn new() -> Self;
  #[allow(async_fn_in_trait)]
  fn init(&self,) -> Result<bool,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn shutdown(&self,) -> Result<bool,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn startjob(&self,job: Job,) -> Result<u64,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn pausejob(&self,id: u64,) -> Result<bool,_rt::String>;
  #[allow(async_fn_in_trait)]
  fn stopjob(&self,id: u64,) -> Result<bool,_rt::String>;
}
#[doc(hidden)]

macro_rules! __export_openfab_drivers_driver_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "openfab:drivers/driver#[constructor]driver")]
    unsafe extern "C" fn export_constructor_driver() -> i32 {
      unsafe { $($path_to_types)*::_export_constructor_driver_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>() }
    }
    #[unsafe(export_name = "openfab:drivers/driver#[method]driver.init")]
    unsafe extern "C" fn export_method_driver_init(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_driver_init_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_openfab:drivers/driver#[method]driver.init")]
    unsafe extern "C" fn _post_return_method_driver_init(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_driver_init::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "openfab:drivers/driver#[method]driver.shutdown")]
    unsafe extern "C" fn export_method_driver_shutdown(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_driver_shutdown_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_openfab:drivers/driver#[method]driver.shutdown")]
    unsafe extern "C" fn _post_return_method_driver_shutdown(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_driver_shutdown::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "openfab:drivers/driver#[method]driver.startjob")]
    unsafe extern "C" fn export_method_driver_startjob(arg0: *mut u8,arg1: i64,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_driver_startjob_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) }
    }
    #[unsafe(export_name = "cabi_post_openfab:drivers/driver#[method]driver.startjob")]
    unsafe extern "C" fn _post_return_method_driver_startjob(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_driver_startjob::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "openfab:drivers/driver#[method]driver.pausejob")]
    unsafe extern "C" fn export_method_driver_pausejob(arg0: *mut u8,arg1: i64,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_driver_pausejob_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_openfab:drivers/driver#[method]driver.pausejob")]
    unsafe extern "C" fn _post_return_method_driver_pausejob(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_driver_pausejob::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }
    #[unsafe(export_name = "openfab:drivers/driver#[method]driver.stopjob")]
    unsafe extern "C" fn export_method_driver_stopjob(arg0: *mut u8,arg1: i64,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_method_driver_stopjob_cabi::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_openfab:drivers/driver#[method]driver.stopjob")]
    unsafe extern "C" fn _post_return_method_driver_stopjob(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_method_driver_stopjob::<<$ty as $($path_to_types)*::Guest>::Driver>(arg0) }
    }

    const _: () = {
      #[doc(hidden)]
      #[unsafe(export_name = "openfab:drivers/driver#[dtor]driver")]
      #[allow(non_snake_case)]
      unsafe extern "C" fn dtor(rep: *mut u8) {
        unsafe {
          $($path_to_types)*::Driver::dtor::<
          <$ty as $($path_to_types)*::Guest>::Driver
          >(rep)
        }
      }
    };
    
  };);
}
#[doc(hidden)]
pub(crate) use __export_openfab_drivers_driver_cabi;

#[repr(align(8))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 8+2*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8+2*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  

  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_drivers_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::openfab::drivers::driver::__export_openfab_drivers_driver_cabi!($ty with_types_in $($path_to_types_root)*::exports::openfab::drivers::driver);
  )
}
#[doc(inline)]
pub(crate) use __export_drivers_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:openfab:drivers:drivers:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 684] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xae\x04\x01A\x02\x01\
A\x04\x01B\x13\x01r\x02\x04names\x08porttype{\x04\0\x08portinfo\x03\0\0\x01p\x01\
\x01j\x01\x02\x01s\x01@\0\0\x03\x04\0\x09listports\x01\x04\x01j\x01s\x01s\x01@\x02\
\x04paths\x08baudratey\0\x05\x04\0\x04open\x01\x06\x01p}\x01j\x01w\x01s\x01@\x02\
\x04paths\x04data\x07\0\x08\x04\0\x05write\x01\x09\x01j\x01\x07\x01s\x01@\x01\x04\
paths\0\x0a\x04\0\x04read\x01\x0b\x01j\x01{\x01s\x01@\x01\x04paths\0\x0c\x04\0\x05\
close\x01\x0d\x03\0\x1aopenfab:drivers/serialport\x05\0\x01B\x12\x01p}\x01r\x04\x02\
idw\x04names\x06formats\x04data\0\x04\0\x03job\x03\0\x01\x04\0\x06driver\x03\x01\
\x01i\x03\x01@\0\0\x04\x04\0\x13[constructor]driver\x01\x05\x01h\x03\x01j\x01\x7f\
\x01s\x01@\x01\x04self\x06\0\x07\x04\0\x13[method]driver.init\x01\x08\x04\0\x17[\
method]driver.shutdown\x01\x08\x01j\x01w\x01s\x01@\x02\x04self\x06\x03job\x02\0\x09\
\x04\0\x17[method]driver.startjob\x01\x0a\x01@\x02\x04self\x06\x02idw\0\x07\x04\0\
\x17[method]driver.pausejob\x01\x0b\x04\0\x16[method]driver.stopjob\x01\x0b\x04\0\
\x16openfab:drivers/driver\x05\x01\x04\0\x17openfab:drivers/drivers\x04\0\x0b\x0d\
\x01\0\x07drivers\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compone\
nt\x070.230.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

